/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package model;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-05-09")
public enum TipProbaDTO implements org.apache.thrift.TEnum {
  desen(1),
  cautare_comori(2),
  poezie(3);

  private final int value;

  private TipProbaDTO(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TipProbaDTO findByValue(int value) { 
    switch (value) {
      case 1:
        return desen;
      case 2:
        return cautare_comori;
      case 3:
        return poezie;
      default:
        return null;
    }
  }
}
