/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-05-08")
public class Inscriere implements org.apache.thrift.TBase<Inscriere, Inscriere._Fields>, java.io.Serializable, Cloneable, Comparable<Inscriere> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Inscriere");

  private static final org.apache.thrift.protocol.TField PARTICIPANT_FIELD_DESC = new org.apache.thrift.protocol.TField("participant", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField PROBA_FIELD_DESC = new org.apache.thrift.protocol.TField("proba", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new InscriereStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new InscriereTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable Participant participant; // required
  public @org.apache.thrift.annotation.Nullable Proba proba; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PARTICIPANT((short)1, "participant"),
    PROBA((short)2, "proba");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PARTICIPANT
          return PARTICIPANT;
        case 2: // PROBA
          return PROBA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PARTICIPANT, new org.apache.thrift.meta_data.FieldMetaData("participant", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Participant.class)));
    tmpMap.put(_Fields.PROBA, new org.apache.thrift.meta_data.FieldMetaData("proba", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Proba.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Inscriere.class, metaDataMap);
  }

  public Inscriere() {
  }

  public Inscriere(
    Participant participant,
    Proba proba)
  {
    this();
    this.participant = participant;
    this.proba = proba;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Inscriere(Inscriere other) {
    if (other.isSetParticipant()) {
      this.participant = new Participant(other.participant);
    }
    if (other.isSetProba()) {
      this.proba = new Proba(other.proba);
    }
  }

  public Inscriere deepCopy() {
    return new Inscriere(this);
  }

  @Override
  public void clear() {
    this.participant = null;
    this.proba = null;
  }

  @org.apache.thrift.annotation.Nullable
  public Participant getParticipant() {
    return this.participant;
  }

  public Inscriere setParticipant(@org.apache.thrift.annotation.Nullable Participant participant) {
    this.participant = participant;
    return this;
  }

  public void unsetParticipant() {
    this.participant = null;
  }

  /** Returns true if field participant is set (has been assigned a value) and false otherwise */
  public boolean isSetParticipant() {
    return this.participant != null;
  }

  public void setParticipantIsSet(boolean value) {
    if (!value) {
      this.participant = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public Proba getProba() {
    return this.proba;
  }

  public Inscriere setProba(@org.apache.thrift.annotation.Nullable Proba proba) {
    this.proba = proba;
    return this;
  }

  public void unsetProba() {
    this.proba = null;
  }

  /** Returns true if field proba is set (has been assigned a value) and false otherwise */
  public boolean isSetProba() {
    return this.proba != null;
  }

  public void setProbaIsSet(boolean value) {
    if (!value) {
      this.proba = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PARTICIPANT:
      if (value == null) {
        unsetParticipant();
      } else {
        setParticipant((Participant)value);
      }
      break;

    case PROBA:
      if (value == null) {
        unsetProba();
      } else {
        setProba((Proba)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PARTICIPANT:
      return getParticipant();

    case PROBA:
      return getProba();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PARTICIPANT:
      return isSetParticipant();
    case PROBA:
      return isSetProba();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Inscriere)
      return this.equals((Inscriere)that);
    return false;
  }

  public boolean equals(Inscriere that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_participant = true && this.isSetParticipant();
    boolean that_present_participant = true && that.isSetParticipant();
    if (this_present_participant || that_present_participant) {
      if (!(this_present_participant && that_present_participant))
        return false;
      if (!this.participant.equals(that.participant))
        return false;
    }

    boolean this_present_proba = true && this.isSetProba();
    boolean that_present_proba = true && that.isSetProba();
    if (this_present_proba || that_present_proba) {
      if (!(this_present_proba && that_present_proba))
        return false;
      if (!this.proba.equals(that.proba))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetParticipant()) ? 131071 : 524287);
    if (isSetParticipant())
      hashCode = hashCode * 8191 + participant.hashCode();

    hashCode = hashCode * 8191 + ((isSetProba()) ? 131071 : 524287);
    if (isSetProba())
      hashCode = hashCode * 8191 + proba.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Inscriere other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetParticipant()).compareTo(other.isSetParticipant());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParticipant()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.participant, other.participant);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetProba()).compareTo(other.isSetProba());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProba()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.proba, other.proba);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Inscriere(");
    boolean first = true;

    sb.append("participant:");
    if (this.participant == null) {
      sb.append("null");
    } else {
      sb.append(this.participant);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("proba:");
    if (this.proba == null) {
      sb.append("null");
    } else {
      sb.append(this.proba);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (participant != null) {
      participant.validate();
    }
    if (proba != null) {
      proba.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class InscriereStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public InscriereStandardScheme getScheme() {
      return new InscriereStandardScheme();
    }
  }

  private static class InscriereStandardScheme extends org.apache.thrift.scheme.StandardScheme<Inscriere> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Inscriere struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PARTICIPANT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.participant = new Participant();
              struct.participant.read(iprot);
              struct.setParticipantIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROBA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.proba = new Proba();
              struct.proba.read(iprot);
              struct.setProbaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Inscriere struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.participant != null) {
        oprot.writeFieldBegin(PARTICIPANT_FIELD_DESC);
        struct.participant.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.proba != null) {
        oprot.writeFieldBegin(PROBA_FIELD_DESC);
        struct.proba.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class InscriereTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public InscriereTupleScheme getScheme() {
      return new InscriereTupleScheme();
    }
  }

  private static class InscriereTupleScheme extends org.apache.thrift.scheme.TupleScheme<Inscriere> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Inscriere struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetParticipant()) {
        optionals.set(0);
      }
      if (struct.isSetProba()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetParticipant()) {
        struct.participant.write(oprot);
      }
      if (struct.isSetProba()) {
        struct.proba.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Inscriere struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.participant = new Participant();
        struct.participant.read(iprot);
        struct.setParticipantIsSet(true);
      }
      if (incoming.get(1)) {
        struct.proba = new Proba();
        struct.proba.read(iprot);
        struct.setProbaIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

