/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-05-08")
public class Proba implements org.apache.thrift.TBase<Proba, Proba._Fields>, java.io.Serializable, Cloneable, Comparable<Proba> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Proba");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField TIP_PROBA_FIELD_DESC = new org.apache.thrift.protocol.TField("tipProba", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField VARSTA_MIN_FIELD_DESC = new org.apache.thrift.protocol.TField("varstaMin", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField VARSTA_MAX_FIELD_DESC = new org.apache.thrift.protocol.TField("varstaMax", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField NR_PARTICIPANTI_FIELD_DESC = new org.apache.thrift.protocol.TField("nrParticipanti", org.apache.thrift.protocol.TType.I32, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ProbaStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ProbaTupleSchemeFactory();

  public int id; // required
  /**
   * 
   * @see TipProba
   */
  public @org.apache.thrift.annotation.Nullable TipProba tipProba; // required
  public int varstaMin; // required
  public int varstaMax; // required
  public int nrParticipanti; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    /**
     * 
     * @see TipProba
     */
    TIP_PROBA((short)2, "tipProba"),
    VARSTA_MIN((short)3, "varstaMin"),
    VARSTA_MAX((short)4, "varstaMax"),
    NR_PARTICIPANTI((short)5, "nrParticipanti");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // TIP_PROBA
          return TIP_PROBA;
        case 3: // VARSTA_MIN
          return VARSTA_MIN;
        case 4: // VARSTA_MAX
          return VARSTA_MAX;
        case 5: // NR_PARTICIPANTI
          return NR_PARTICIPANTI;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __VARSTAMIN_ISSET_ID = 1;
  private static final int __VARSTAMAX_ISSET_ID = 2;
  private static final int __NRPARTICIPANTI_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TIP_PROBA, new org.apache.thrift.meta_data.FieldMetaData("tipProba", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, TipProba.class)));
    tmpMap.put(_Fields.VARSTA_MIN, new org.apache.thrift.meta_data.FieldMetaData("varstaMin", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.VARSTA_MAX, new org.apache.thrift.meta_data.FieldMetaData("varstaMax", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NR_PARTICIPANTI, new org.apache.thrift.meta_data.FieldMetaData("nrParticipanti", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Proba.class, metaDataMap);
  }

  public Proba() {
  }

  public Proba(
    int id,
    TipProba tipProba,
    int varstaMin,
    int varstaMax,
    int nrParticipanti)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.tipProba = tipProba;
    this.varstaMin = varstaMin;
    setVarstaMinIsSet(true);
    this.varstaMax = varstaMax;
    setVarstaMaxIsSet(true);
    this.nrParticipanti = nrParticipanti;
    setNrParticipantiIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Proba(Proba other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetTipProba()) {
      this.tipProba = other.tipProba;
    }
    this.varstaMin = other.varstaMin;
    this.varstaMax = other.varstaMax;
    this.nrParticipanti = other.nrParticipanti;
  }

  public Proba deepCopy() {
    return new Proba(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.tipProba = null;
    setVarstaMinIsSet(false);
    this.varstaMin = 0;
    setVarstaMaxIsSet(false);
    this.varstaMax = 0;
    setNrParticipantiIsSet(false);
    this.nrParticipanti = 0;
  }

  public int getId() {
    return this.id;
  }

  public Proba setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  /**
   * 
   * @see TipProba
   */
  @org.apache.thrift.annotation.Nullable
  public TipProba getTipProba() {
    return this.tipProba;
  }

  /**
   * 
   * @see TipProba
   */
  public Proba setTipProba(@org.apache.thrift.annotation.Nullable TipProba tipProba) {
    this.tipProba = tipProba;
    return this;
  }

  public void unsetTipProba() {
    this.tipProba = null;
  }

  /** Returns true if field tipProba is set (has been assigned a value) and false otherwise */
  public boolean isSetTipProba() {
    return this.tipProba != null;
  }

  public void setTipProbaIsSet(boolean value) {
    if (!value) {
      this.tipProba = null;
    }
  }

  public int getVarstaMin() {
    return this.varstaMin;
  }

  public Proba setVarstaMin(int varstaMin) {
    this.varstaMin = varstaMin;
    setVarstaMinIsSet(true);
    return this;
  }

  public void unsetVarstaMin() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VARSTAMIN_ISSET_ID);
  }

  /** Returns true if field varstaMin is set (has been assigned a value) and false otherwise */
  public boolean isSetVarstaMin() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VARSTAMIN_ISSET_ID);
  }

  public void setVarstaMinIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VARSTAMIN_ISSET_ID, value);
  }

  public int getVarstaMax() {
    return this.varstaMax;
  }

  public Proba setVarstaMax(int varstaMax) {
    this.varstaMax = varstaMax;
    setVarstaMaxIsSet(true);
    return this;
  }

  public void unsetVarstaMax() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VARSTAMAX_ISSET_ID);
  }

  /** Returns true if field varstaMax is set (has been assigned a value) and false otherwise */
  public boolean isSetVarstaMax() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VARSTAMAX_ISSET_ID);
  }

  public void setVarstaMaxIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VARSTAMAX_ISSET_ID, value);
  }

  public int getNrParticipanti() {
    return this.nrParticipanti;
  }

  public Proba setNrParticipanti(int nrParticipanti) {
    this.nrParticipanti = nrParticipanti;
    setNrParticipantiIsSet(true);
    return this;
  }

  public void unsetNrParticipanti() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NRPARTICIPANTI_ISSET_ID);
  }

  /** Returns true if field nrParticipanti is set (has been assigned a value) and false otherwise */
  public boolean isSetNrParticipanti() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NRPARTICIPANTI_ISSET_ID);
  }

  public void setNrParticipantiIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NRPARTICIPANTI_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Integer)value);
      }
      break;

    case TIP_PROBA:
      if (value == null) {
        unsetTipProba();
      } else {
        setTipProba((TipProba)value);
      }
      break;

    case VARSTA_MIN:
      if (value == null) {
        unsetVarstaMin();
      } else {
        setVarstaMin((java.lang.Integer)value);
      }
      break;

    case VARSTA_MAX:
      if (value == null) {
        unsetVarstaMax();
      } else {
        setVarstaMax((java.lang.Integer)value);
      }
      break;

    case NR_PARTICIPANTI:
      if (value == null) {
        unsetNrParticipanti();
      } else {
        setNrParticipanti((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case TIP_PROBA:
      return getTipProba();

    case VARSTA_MIN:
      return getVarstaMin();

    case VARSTA_MAX:
      return getVarstaMax();

    case NR_PARTICIPANTI:
      return getNrParticipanti();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case TIP_PROBA:
      return isSetTipProba();
    case VARSTA_MIN:
      return isSetVarstaMin();
    case VARSTA_MAX:
      return isSetVarstaMax();
    case NR_PARTICIPANTI:
      return isSetNrParticipanti();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Proba)
      return this.equals((Proba)that);
    return false;
  }

  public boolean equals(Proba that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_tipProba = true && this.isSetTipProba();
    boolean that_present_tipProba = true && that.isSetTipProba();
    if (this_present_tipProba || that_present_tipProba) {
      if (!(this_present_tipProba && that_present_tipProba))
        return false;
      if (!this.tipProba.equals(that.tipProba))
        return false;
    }

    boolean this_present_varstaMin = true;
    boolean that_present_varstaMin = true;
    if (this_present_varstaMin || that_present_varstaMin) {
      if (!(this_present_varstaMin && that_present_varstaMin))
        return false;
      if (this.varstaMin != that.varstaMin)
        return false;
    }

    boolean this_present_varstaMax = true;
    boolean that_present_varstaMax = true;
    if (this_present_varstaMax || that_present_varstaMax) {
      if (!(this_present_varstaMax && that_present_varstaMax))
        return false;
      if (this.varstaMax != that.varstaMax)
        return false;
    }

    boolean this_present_nrParticipanti = true;
    boolean that_present_nrParticipanti = true;
    if (this_present_nrParticipanti || that_present_nrParticipanti) {
      if (!(this_present_nrParticipanti && that_present_nrParticipanti))
        return false;
      if (this.nrParticipanti != that.nrParticipanti)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + id;

    hashCode = hashCode * 8191 + ((isSetTipProba()) ? 131071 : 524287);
    if (isSetTipProba())
      hashCode = hashCode * 8191 + tipProba.getValue();

    hashCode = hashCode * 8191 + varstaMin;

    hashCode = hashCode * 8191 + varstaMax;

    hashCode = hashCode * 8191 + nrParticipanti;

    return hashCode;
  }

  @Override
  public int compareTo(Proba other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTipProba()).compareTo(other.isSetTipProba());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTipProba()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tipProba, other.tipProba);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetVarstaMin()).compareTo(other.isSetVarstaMin());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVarstaMin()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.varstaMin, other.varstaMin);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetVarstaMax()).compareTo(other.isSetVarstaMax());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVarstaMax()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.varstaMax, other.varstaMax);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNrParticipanti()).compareTo(other.isSetNrParticipanti());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNrParticipanti()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nrParticipanti, other.nrParticipanti);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Proba(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("tipProba:");
    if (this.tipProba == null) {
      sb.append("null");
    } else {
      sb.append(this.tipProba);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("varstaMin:");
    sb.append(this.varstaMin);
    first = false;
    if (!first) sb.append(", ");
    sb.append("varstaMax:");
    sb.append(this.varstaMax);
    first = false;
    if (!first) sb.append(", ");
    sb.append("nrParticipanti:");
    sb.append(this.nrParticipanti);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ProbaStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ProbaStandardScheme getScheme() {
      return new ProbaStandardScheme();
    }
  }

  private static class ProbaStandardScheme extends org.apache.thrift.scheme.StandardScheme<Proba> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Proba struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.id = iprot.readI32();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TIP_PROBA
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.tipProba = TipProba.findByValue(iprot.readI32());
              struct.setTipProbaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // VARSTA_MIN
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.varstaMin = iprot.readI32();
              struct.setVarstaMinIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // VARSTA_MAX
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.varstaMax = iprot.readI32();
              struct.setVarstaMaxIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // NR_PARTICIPANTI
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.nrParticipanti = iprot.readI32();
              struct.setNrParticipantiIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Proba struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      if (struct.tipProba != null) {
        oprot.writeFieldBegin(TIP_PROBA_FIELD_DESC);
        oprot.writeI32(struct.tipProba.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(VARSTA_MIN_FIELD_DESC);
      oprot.writeI32(struct.varstaMin);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(VARSTA_MAX_FIELD_DESC);
      oprot.writeI32(struct.varstaMax);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NR_PARTICIPANTI_FIELD_DESC);
      oprot.writeI32(struct.nrParticipanti);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ProbaTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ProbaTupleScheme getScheme() {
      return new ProbaTupleScheme();
    }
  }

  private static class ProbaTupleScheme extends org.apache.thrift.scheme.TupleScheme<Proba> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Proba struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetTipProba()) {
        optionals.set(1);
      }
      if (struct.isSetVarstaMin()) {
        optionals.set(2);
      }
      if (struct.isSetVarstaMax()) {
        optionals.set(3);
      }
      if (struct.isSetNrParticipanti()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetTipProba()) {
        oprot.writeI32(struct.tipProba.getValue());
      }
      if (struct.isSetVarstaMin()) {
        oprot.writeI32(struct.varstaMin);
      }
      if (struct.isSetVarstaMax()) {
        oprot.writeI32(struct.varstaMax);
      }
      if (struct.isSetNrParticipanti()) {
        oprot.writeI32(struct.nrParticipanti);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Proba struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.id = iprot.readI32();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.tipProba = TipProba.findByValue(iprot.readI32());
        struct.setTipProbaIsSet(true);
      }
      if (incoming.get(2)) {
        struct.varstaMin = iprot.readI32();
        struct.setVarstaMinIsSet(true);
      }
      if (incoming.get(3)) {
        struct.varstaMax = iprot.readI32();
        struct.setVarstaMaxIsSet(true);
      }
      if (incoming.get(4)) {
        struct.nrParticipanti = iprot.readI32();
        struct.setNrParticipantiIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

